### ISSUE TITLE
EPIC: Retry mechanisme voor notificatieberichten

### ISSUE THREAD

**Issue by Aad1407** [Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening#189]
***Als*** beheerder

***Wil ik***  zo min mogelijk tijd kwijt zijn met herstelacties als gevolg van niet-afgeleverde notificaties

***Zodat*** ik deze tijd kan besteden aan andere werkzaamheden 

#14 

Voorbesproken met Joeri Diederen, Erik Christiaens, Waris Amanzai en Andy Verberne

**Comment by joeridiederen** [comment]
@Aad1407 : Het retry-mechanisme van Open Zaak (eigenlijk Open Notificaties) is ook klaar: https://github.com/open-zaak/open-zaak/issues/1204

**Comment by PaskalKiers** [comment]
Verzamelepic voor:

- [ ] Dimpact-Samenwerking/PodiumD#190
- [ ] Dimpact-Samenwerking/PodiumD#191
- [ ] Dimpact-Samenwerking/PodiumD#192

**Comment by PaskalKiers** [comment]
Gerelateerd aan WIJZ-649 in het DIMPACT JIRA

**Comment by StefSchots1993** [comment]
Opnieuw bij ATOS aangeboden onder https://support.dimpact.nl/jira/browse/WIJZ-657
