### ISSUE TITLE
Uitwerking Koppeling OF-eSuite

### ISSUE THREAD

**Issue by PaskalKiers** [Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening#202]
***Als*** koplopergroep OF

***Wil ik*** een zaak kunnen starten op basis van formulierdata uit open Formulieren 

***Zodat*** ik open formulieren kan gebruiken om internetaanvragen te laten doen.

Acceptatiecriteria:
De eSuite is loosely coupled via een productaanvraag in de ORC en Open notificaties aan Open Formulieren.
De koppeling heeft één schema voor de productaanvraag in de ORC

Dit workitem is vooral opgesteld als referentie tegenover het workitem in de relevante Atos repository.

Details zijn verder toegelicht in de open formulieren repository in:

- [ ] Dimpact-Samenwerking/Open-Formulieren#103
- [ ] Dimpact-Samenwerking/Open-Formulieren#117
- [ ] Dimpact-Samenwerking/Open-Formulieren#113
- [ ] Dimpact-Samenwerking/Open-Formulieren#104
- [ ] Dimpact-Samenwerking/Open-Formulieren#105
- [ ] Dimpact-Samenwerking/Open-Formulieren#106
- [x] Dimpact-Samenwerking/Open-Formulieren#108
- [x] Dimpact-Samenwerking/Open-Formulieren#109
- [ ] Dimpact-Samenwerking/Open-Formulieren#121
- [x] Dimpact-Samenwerking/Open-Formulieren#163
- [ ] Dimpact-Samenwerking/PodiumD#180

Is een uitwerking van #179

**Comment by PaskalKiers** [comment]
ter referentie een epic over het handmatig afhandelen van een productaanvraag uit de ZAC repo: NL-AMS-LOCGOV/zaakafhandelcomponent#319
Een voorbeld van ander gebruik van het productaanvraag patroon.
