### ISSUE TITLE
Restpunten Story aanmaken zaak in eSuite op basis van productaanvraag

### ISSUE THREAD

**Issue by PaskalKiers** [Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening#203]
#89 is aan Atos en Dimpactzijde gesloten zonder dat het getest kon worden (als gevolg van omgevingsproblemen). 
Van hetgeen getest kon worden is een nieuwe story gemaakt, omdat de oplossing niet voldeed.  Deze story is om voor oplevering te toetsen of de oplossing aan de acceptatiecriteria voldoet (en adequate actie te ondernemen als er niet aan voldaan is).

**Als** Productowner eSuite
**wil ik** dat de e-Suite een zaak aan kan maken op basis van de opgehaalde productaanvraaginformatie
**zodat** ik Open formulieren kan gebruiken om aanvraaginformatie (van burgers) te verzamelen.

Acceptatiecriteria:
- [ ] De aanvrager heeft één nummer teruggekoppeld gekregen, op basis waarvan hij/zij de zaak kan volgen.
- [X] De resulterende zaak is te behandelen via het bestaande e-Suite proces (op basis van het zaaktype) -->  apart geregistreerd in Dimpact-Samenwerking/Open-Formulieren#182
- [ ] De documenten zijn benaderbaar vanuit de zaak
- [ ] De rollen zijn gekoppeld aan de zaak
- [ ] De zaak is toegewezen aan de ingestelde groep / behandelaar.
- [ ] De zaak is vindbaar door de servicedesk onder het referentienummer dat teruggekoppeld is aan de indiener.
- [ ] De zaak is vindbaar door de indiener in de loketfunctionaliteit onder het referentienummer dat teruggekoppeld is aan de indiener. (waarschijnlijk loketstory voor Rotterdam)
- [ ] De gegevens uit de productaanvraag zijn beschikbaar in de zaaktaken (mits ze aangeroepen worden in de taak).
